### ISSUE TITLE
Error Validating Model

### ISSUE THREAD

**Issue by jonathanloganmoran** [jonathanloganmoran/emotion-recognition-neural-networks#1]
Attempting to test the fully-trained network against the `FER2013` `image_test` validation dataset using the `manual_poc.py` script. 

When running `$ python manual_poc.py`, no output confusion matrix is generated.

Stack trace: 
> [+] Loading Data
Traceback (most recent call last):
  File "plot_emotion_matrix.py", line 23, in <module>
    data[np.argmax(labels[i]), result[0].index(max(result[0]))] += 1
AttributeError: 'numpy.ndarray' object has no attribute 'index'

**Comment by jonathanloganmoran** [comment]
# Update 5/21:
Naming conflict with saved weights was resolved:

- [X] corrupt training data in `Gudi_model_100_epochs_20000_faces.index` was discarded

- [X] `Gudi_model_100_epochs_20000_faces.data-00000-of-00001` renamed to `Gudi_model_100_epochs_20000_faces` to match `constants.py` import path

# Current issue: 
Table file data is corrupt/unable to be read. Will check extension format

Stack trace: 
> DataLossError (see above for traceback): Unable to open table file /Users/jonathanmoran/Desktop/emotion-recognition-CNN/data/Gudi_model_100_epochs_20000_faces.data: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]

**Comment by jonathanloganmoran** [comment]
# Update 5/23:
Removed the `.data` extension from the saved weights file

- [X] Fix Current issue #1 (see above solution)

- [ ]  Fix `AttributeError` in `plot_emotion_matrix.py`

Stack trace (when attempting `$ python plot_emotion_matrix.py`):

> [+] Loading Data
Traceback (most recent call last):
  File "plot_emotion_matrix.py", line 23, in <module>
    data[np.argmax(labels[i]), result[0].index(max(result[0]))] += 1
AttributeError: 'numpy.ndarray' object has no attribute 'index'

**Comment by jonathanloganmoran** [comment]
# Update 6/1:
Added the `tolist()` extension to `line 23`: `result[0].tolist().index(max ... ))] += 1`
- [X] Fix `AttributeError` in `plot_emotion_matrix.py (see above fix)

- [ ] Print expected confusion matrix
Current confusion matrix contains erroneous data. Will have to debug training weights/test set to understand why predictions are not accurate
